"""Add prompt analysis fields to GeneratedPrompt

Revision ID: 1f4039363db1
Revises: fdfcc7a8d317
Create Date: 2025-09-13 14:29:56.991237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f4039363db1'
down_revision = 'fdfcc7a8d317'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generated_prompt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('overall_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('clarity', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('specificity', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('effectiveness', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('refined_prompt', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('improvements_made', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('additional_suggestions', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generated_prompt', schema=None) as batch_op:
        batch_op.drop_column('additional_suggestions')
        batch_op.drop_column('improvements_made')
        batch_op.drop_column('refined_prompt')
        batch_op.drop_column('effectiveness')
        batch_op.drop_column('specificity')
        batch_op.drop_column('clarity')
        batch_op.drop_column('overall_score')

    # ### end Alembic commands ###
