"""Initial migration.

Revision ID: 95c5de4a7aa8
Revises: 
Create Date: 2025-09-13 15:50:01.689039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95c5de4a7aa8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('prompt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('intended_use', sa.String(length=200), nullable=True),
    sa.Column('target_audience', sa.String(length=200), nullable=True),
    sa.Column('expected_outcome', sa.String(length=200), nullable=True),
    sa.Column('tags', sa.String(length=200), nullable=True),
    sa.Column('is_shared', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generated_prompt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prompt_id', sa.Integer(), nullable=False),
    sa.Column('generated_text', sa.Text(), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=True),
    sa.Column('clarity', sa.Integer(), nullable=True),
    sa.Column('specificity', sa.Integer(), nullable=True),
    sa.Column('effectiveness', sa.Integer(), nullable=True),
    sa.Column('refined_prompt', sa.Text(), nullable=True),
    sa.Column('improvements_made', sa.JSON(), nullable=True),
    sa.Column('additional_suggestions', sa.JSON(), nullable=True),
    sa.Column('prompt_token_count', sa.Integer(), nullable=True),
    sa.Column('candidates_token_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompt.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('generated_prompt')
    op.drop_table('prompt')
    op.drop_table('user')
    # ### end Alembic commands ###
